name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/checkout@v3
    - name: Get API Key
      env:
        KRDICT_API_KEY: ${{ secrets.KRDICT_API_KEY}}
      run: |
        echo $KRDICT_API_KEY >> .apikey
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
